### ISSUE TITLE
Invalid Arguments

### ISSUE THREAD

**Issue by James-buzz** [IceTank/mineflayer-panorama#1]
When I try to take an picture I get the error "invalid arguments". Please help
I'm using the code from the example. 

`const mineflayer = require('mineflayer');
const { Titles } = require('prismarine-auth');
const panorama = require('./mineflayer-panorama/index').image;
const fs = require('fs');
const { Vec3 } = require('vec3');

const bot = mineflayer.createBot({
  host: 'localhost',
  username: 'jameslomax96@gmail.com',
  password: 'RandomPasswordHa',
  auth: 'microsoft',
  authTitle: Titles.MinecraftJava,
});

bot.on('spawn', async () => {
  console.info('Bot spawned');
  bot.loadPlugin(panorama);
  await bot.waitForChunksToLoad();
  console.info('Ready to use');
  // Take screenshots
  const botPos = bot.entity.position;
  const directions = [new Vec3(1, 0, 0), new Vec3(-1, 0, 0), new Vec3(0, 1, 0), new Vec3(0, -1, 0), new Vec3(0, 0, -1), new Vec3(0, 0, 1)];
  try {
    let { pitch, yaw } = bot.entity;
    let direction = getViewVector(pitch, yaw);
    await takePicture('next', bot.entity.position.offset(0, bot.entity.height, 0), direction);
    bot.chat('Took picture ' + 'next' + '.jpg');
  } catch (e) {
    console.error(e);
  }
});

let imageCounter = 0;

async function takePicture(fileName, pos, direction) {
  if (fileName === 'next') {
    fileName = 'image' + String(imageCounter).padStart(4, '0');
    imageCounter++;
  }
  console.info('Checking files');
  let stats;
  try {
    stats = await fs.promises.stat('./screenshots');
  } catch (e) {
    if (!stats?.isDirectory()) {
      console.info('Making new folder screenshots');
      await fs.promises.mkdir('./screenshots');
    }
  }
  console.info('Taking image');
  const fileStream = await bot.image.takePicture(pos, direction);
  console.info('Writing file');
  const file = fs.createWriteStream('./screenshots/' + fileName + '.jpg');
  fileStream.pipe(file);
  fileStream.on('error', (err) => {
    console.error(err);
  });
  return new Promise((resolve) => {
    file.on('finish', () => {
      resolve(fileName);
    });
  });
}

function isVec(obj) {
  if (!obj) return false;
  return obj instanceof Vec3;
}

function getViewVector(pitch, yaw) {
  const csPitch = Math.cos(pitch);
  const snPitch = Math.sin(pitch);
  const csYaw = Math.cos(yaw);
  const snYaw = Math.sin(yaw);
  return new Vec3(-snYaw * csPitch, snPitch, -csYaw * csPitch);
}
`

**Comment by IceTank** [comment]
Can you provide the exact error message? Also what system are you running this on? Are you sure npm install worked correctly and installed everything without errors? Are you running the example from inside a docker container or without one?
